tap_install:
  values:
    profile: full # Can take iterate, build, run, view.
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.
    
    shared:
      ingress_domain: "tap.h2o-2-23830.h2o.vmware.com"
      ingress_issuer: "tap-ingress-selfsigned" # Optional, can denote a cert-manager.io/v1/ClusterIssuer of your choice. Defaults to "tap-ingress-selfsigned".
    
      image_registry:
        project_path: "harbor.h2o-2-23830.h2o.vmware.com/tap"
        secret:
          name: "registry-credentials"
          namespace: "tap-install"
    
    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.
    
    #Below are the keys which may have default values set, but can be overridden.
    
    supply_chain: testing_scanning # Can take basic, testing, testing_scanning.
    
    ootb_supply_chain_testing_scanning: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
      source:
        credentials_secret: "" # (Optional) Defaults to "".
      registry:
        server: "harbor.h2o-2-23830.h2o.vmware.com" # Takes the value from the shared section by default, but can be overridden by setting a different value.
        repository: "tap-apps/supply-chain" # Takes the value from the shared section by default, but can be overridden by setting a different value.
    
    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.
    
    buildservice:
      # Takes the value from the shared section by default, but can be overridden by setting a different value.
      kp_default_repository: "harbor.h2o-2-23830.h2o.vmware.com/build/tbs"
      kp_default_repository_secret: # Takes the value from the shared section above by default, but can be overridden by setting a different value.
        name: "tap-registry"
        namespace: "tap-install"
      exclude_dependencies: true
    
    local_source_proxy:
      # Takes the value from the project_path under the image_registry section of shared by default, but can be overridden by setting a different value.
      repository: ""
      push_secret:
        # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
        name: "registry-credentials"
        namespace: "tap-install"
        # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
        create_export: true
    
    tap_gui:
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Developer Portal and SCST - Store.
      app_config:
        auth:
          loginPage:
            github:
              title: TAP Login with Github
              message: Enter with your GitHub account
        catalog:
          locations:
            - type: url
              target: https://github.com/bzhtux/tap-catalog/blob/main/catalog-info.yaml
        app:
          baseUrl: https://tap-gui.tap.h2o-2-23830.h2o.vmware.com
        backend:
          baseUrl: https://tap-gui.tap.h2o-2-23830.h2o.vmware.com
          cors:
            origin: https://tap-gui.tap.h2o-2-23830.h2o.vmware.com
          reading:
            allow:
              - host: '*.h2o-2-23830.h2o.vmware.com'
    
    metadata_store:
      ns_for_export_app_cert: "*" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.
    
    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
    tap_telemetry:
      customer_entitlement_account_number: "" # (Optional) Identify data for creating the Tanzu Application Platform usage reports.
