---
tap_install:
  secrets:
    eso:
      vault:
        server: 10.214.148.124
        namespace: ""
        auth:
          kubernetes:
            mountPath: tap-build
            role: tap-build--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: secret/dev/tap-build/tap/sensitive-values.yaml
